@rootUrl = http://localhost:3000

### post create task
POST {{rootUrl}}/api/create-task
Content-Type: application/json

{}

### post login
POST {{rootUrl}}/api/login
Content-Type: application/json

{
  "username": "admin",
  "password": "password1234"
}

### post logout
POST {{rootUrl}}/api/logout
